# Generated by Django 2.2.4 on 2022-09-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='ninja',
            new_name='dojo',
        ),
    ]
